### ISSUE TITLE
Class 'XMLReader' not found in WXRImporter.php:123

### ISSUE THREAD

**Issue by anteksiler** [proteusthemes/one-click-demo-import#110]
One client of ours is getting the error in title. He 's using PHP 7.0.

Exact path: one-click-demo-import/vendor/proteusthemes/wp-content-importer-v2/src/WXRImporter.php:123

**Comment by primozcigler** [comment]
Hi,

Their hosting has XML module disabled in the php config. This is not usual because XML modules come out of the box with the PHP config for the prod.

Can you confirm that's an issue? Try to get a `phpinfo();` from them.

**Comment by volaka** [comment]
Hi, 

@primozcigler I am having the same error:

[06-Dec-2017 11:20:56 UTC] PHP Fatal error:  Uncaught Error: Class 'XMLReader' not found in /var/www/html/wp-content/plugins/one-click-demo-import/vendor/proteusthemes/wp-content-importer-v2/src/WXRImporter.php:123

PHP Version 7.0.22-0ubuntu0.16.04.1

libxml is enabled also. 
![phpinfo](https://user-images.githubusercontent.com/13176256/33659436-3e2fcb30-da91-11e7-8a6f-564640e2d015.png)

Full stack trace is below:
```
[06-Dec-2017 11:20:56 UTC] PHP Fatal error:  Uncaught Error: Class 'XMLReader' not found in /var/www/html/wp-content/plugins/one-click-demo-import/vendor/proteusthemes/wp-content-importer-v2/src/WXRImporter.php:123
Stack trace:
#0 /var/www/html/wp-content/plugins/one-click-demo-import/vendor/proteusthemes/wp-content-importer-v2/src/WXRImporter.php(331): ProteusThemes\WPContentImporter2\WXRImporter->get_reader('/var/www/html/w...')
#1 /var/www/html/wp-content/plugins/one-click-demo-import/inc/Importer.php(80): ProteusThemes\WPContentImporter2\WXRImporter->import('/var/www/html/w...')
#2 /var/www/html/wp-content/plugins/one-click-demo-import/inc/Importer.php(137): OCDI\Importer->import('/var/www/html/w...')
#3 /var/www/html/wp-content/plugins/one-click-demo-import/inc/OneClickDemoImport.php(287): OCDI\Importer->import_content('/var/www/html/w...')
#4 /var/www/html/wp-includes/class-wp-hook.php(298): OCDI\OneClickDemoImport->import_demo_data_ajax_callback('')
#5 /var/www/html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#6 /var/www in /var/www/html/wp-content/plugins/one-click-demo-import/vendor/proteusthemes/wp-content-importer-v2/src/WXRImporter.php on line 123
```
--
Do you have any idea why this can be hapenning?
Thanks,

**Comment by volaka** [comment]
Problem is solved, I manually installed php-xml and that resolved the issue i guess.

**Comment by primozcigler** [comment]
Awesome, thanks for letting us know (and everyone else that might encounter this issue in the future)!

**Comment by hassanabbasi** [comment]
I am having same issue. I'm using PHP 7.2.5 and my phpinfo is showing that libxml is enabled.
I tried installing php-xml manually but it still not resolved the problem. 
![screen shot 2018-06-21 at 9 16 21 am](https://user-images.githubusercontent.com/1093954/41697804-050b0732-7534-11e8-8c62-afc460762b25.png)

**Comment by capuderg** [comment]
Hi @hassanabbasi,

and you get the same error?
> PHP Fatal error:  Uncaught Error: Class 'XMLReader' not found ...

Could you please contact your hosting and ask them, to install php-xml for you?

There is no other way, but this: PHP does not have access to the XMLReader class and that's why the error shows up.

Take care!

**Comment by hassanabbasi** [comment]
@capuderg I am trying to do this on AWS EC2 instance, and I already tried installing php-xml but it's not working.

**Comment by capuderg** [comment]
I'm no server expert, but did you try to install your PHP version specific lib?

`sudo apt-get install php7.2-xml`

And restart the server?

**Comment by azghanvi** [comment]
Had this issue in docker alpine php, worked by following steps:

apk add php7-xmlreader
httpd -k stop
httpd -k start

Don't forget to restart apache.

**Comment by taragurung** [comment]
sudo apt install php8.1-xml. Install the xml as per your PHP version
